name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem?
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
